// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { Database } from './types';

const SUPABASE_URL = "https://fqbwglmbdmfnmgllkdgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxYndnbG1iZG1mbm1nbGxrZGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MzU4MDUsImV4cCI6MjA4NTExMTgwNX0.p9ZfcEywVJvj7Y7y90STU3rzgGsX3kJxLmkLKkwQKfA";

// React Native uses AsyncStorage instead of localStorage
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: AsyncStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});
